### ISSUE TITLE
question: Timeline for releasing `0.2.3`

### ISSUE THREAD

**Issue by ParkMyCar** [sagebind/castaway#18]
Hey @sagebind! I was wondering if you had an idea when you'd be releasing a new version of `castaway`? We use it in `compact_str` and need the new version to fix this issue: https://github.com/ParkMyCar/compact_str/issues/304. Absolutely no rush at all, was just curious if you had a timeline, thanks!

**Comment by dragazo** [comment]
Friendly bump just to keep it on the radar. Still no rush, though!

**Comment by NobodyXu** [comment]
Pinging cc @sagebind can we create a new releae please?

BTW I can volunteer to be the maintainer if you are too busy

**Comment by sagebind** [comment]
Sorry this slipped under my radar for so long! I won't be able to make a release this week, but by the 16th I should have a lighter workload and will make a note to create a new release if I am able.

**Comment by NobodyXu** [comment]
Thank you!

If you are busy, then I can volunteer to be the maintainer of this crate, if you could invite me to this GitHub repository and the crates.io, then I can cut the release.

**Comment by sagebind** [comment]
It has [now been released](https://github.com/sagebind/castaway/releases/tag/0.2.3)! Thank you for your extreme patience.
